
REPLACE INTO `mangos_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES
-- Add texts for personal xp rate command.
(183, 'You can''t set XP rate below %g!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(184, 'You can''t set XP rate above %g!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(185, 'You have changed %s XP rate to %g times normal experience gain.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
-- Add texts for cheat command.
(900,'You set instant casting mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(901,'Your instant casting mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(902,'NO POWER COST cheat is ON',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(903,'NO POWER COST cheat is OFF',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(904,'You set no power cost mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(905,'Your no power cost mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(906,'DEBUFF IMMUNITY cheat is ON',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(907,'DEBUFF IMMUNITY cheat is OFF',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(908,'You set debuff immunity mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(909,'Your debuff immunity mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(910,'ALWAYS CRIT cheat is ON',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(911,'ALWAYS CRIT cheat is OFF',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(912,'You set always crit mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(913,'Your always crit mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(914,'NO CAST CHECKS cheat is ON',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(915,'NO CAST CHECKS cheat is OFF',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(916,'You set no cast checks mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(917,'Your no cast checks mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(918,'ALWAYS PROC cheat is ON',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(919,'ALWAYS PROC cheat is OFF',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(920,'You set always proc mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(921,'Your always proc mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(922,'TRIGGER PASS cheat is ON',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(923,'TRIGGER PASS cheat is OFF',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(924,'You set trigger pass mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(925,'Your trigger pass mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(926,'IGNORE TRIGGERS cheat is ON',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(927,'IGNORE TRIGGERS cheat is OFF',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(928,'You set ignore triggers mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(929,'Your ignore triggers mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(930,'GOD mode is ON',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(931,'GOD mode is OFF',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(932,'You set wallclimb mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(933,'Your wallclimb mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(934,'NO COOLDOWN cheat is ON',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(935,'NO COOLDOWN cheat is OFF',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(936,'You set no cooldown mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(937,'Your no cooldown mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(938,'You set god mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(939,'Your god mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(940,'You set immune to players mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(941,'Your immune to players mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(942,'You set immune to creatures mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(943,'Your immune to creatures mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(944,'You set untargetable mode to %s for %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(945,'Your untargetable mode has been turned %s by %s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(946,'INSTACAST cheat is ON',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(947,'INSTACAST cheat is OFF',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
