option(DEBUG                "Include additional debug-code in core"    OFF)
option(WARNINGS             "Show all warnings during compile"         OFF)
option(PCH                  "Use precompiled headers"                  ON )
option(BUILD_GAME_SERVER    "Build game server"                        ON )
option(BUILD_LOGIN_SERVER   "Build login server"                       OFF)
option(BUILD_EXTRACTORS     "Build map/dbc/vmap/mmap extractors"       OFF)
option(BUILD_SCRIPTDEV      "Build ScriptDev. (OFF Speedup build)"     ON )
option(BUILD_PLAYERBOT      "Build Playerbot mod"                      OFF)
option(BUILD_AHBOT          "Build Auction House Bot mod"              OFF)
